language: scala
scala:
- 2.12.7
- 2.11.12
jdk:
- oraclejdk8
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/20b8e51c61363eee95e8
    on_success: change
    on_failure: always
    on_start: false
  email:
  - truffaut.julien@gmail.com
script:
  - sbt ++$TRAVIS_SCALA_VERSION monocle${TARGET}/$PRE
  - sbt ++$TRAVIS_SCALA_VERSION monocle${TARGET}/test packageSrc
  - |
    if [ $TARGET = JVM && $TRAVIS_SCALA_VERSION == 2.12.7 ]; then
      sbt ++$TRAVIS_SCALA_VERSION tut
    else
      echo "Skipping sbt tut"
    fi
env:
  global:
    - secure: lJxaR+9VM96s7rfaigL3K2FbcP3XiZ+AerbgOBOpYi2anRkMPQ91h1g60HYTwEDGJIKybyNWFuXZM8hNtQMCxzxgu7ev1SyRr5Otfzg5ehGqB5UWbSAgpXlqhR5dAonwmqyEEDF2OK+k1fa0N6mIwpQeuUCwrt68kTp4f0K9jMQ=
    - secure: NZQn8lB04I+FO3Om680CXWP29scS/zRhITbLO/1sM3dnuG8ygn0fzlFMQhgCO3fCjnclThAi+6MN7UnyV8BwDbFhCDe627+06px5fHUw2TPdzhz/BwngAW9pRsx6m0b8eBqQmt8Q6mlgeYOPemsFOeqQTKZulpIhSYnO1R1Nwzc=
  matrix:
    - TARGET=JVM PRE=test:compile
    - TARGET=JS  PRE=test:fastOptJS
sudo: true
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_install:
 - export PATH=${PATH}:./vendor/bundle
before_script:
  - sudo chmod +x /usr/local/bin/sbt
install:
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1
after_success:
- '[[ $TRAVIS_BRANCH == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]] && { sbt +publish ghpagesPushSite; };'
matrix:
  include:
  - scala: 2.11.11
    jdk: oraclejdk8
    sudo: required
    before_install:
    - sudo apt-get update
    - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -
    script:
    - sbt ++$TRAVIS_SCALA_VERSION testNative/run
  - scala: 2.13.0-M5
    script:
    - sbt "++${TRAVIS_SCALA_VERSION}!"
      bench/compile
      stateJVM/compile
      unsafeJVM/compile
      lawJVM/compile
      genericJS/compile
      macrosJS/compile
      stateJS/compile
      unsafeJS/compile
      lawJS/compile
