language: scala
scala:
- 2.12.2
- 2.11.8
- 2.10.6
jdk:
- oraclejdk8
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/20b8e51c61363eee95e8
    on_success: change
    on_failure: always
    on_start: false
  email:
  - truffaut.julien@gmail.com
script:
  - sbt ++$TRAVIS_SCALA_VERSION monocle${TARGET}/$PRE
  - sbt ++$TRAVIS_SCALA_VERSION monocle${TARGET}/test packageSrc
  - |
    if [ $TARGET = JVM && $TRAVIS_SCALA_VERSION == 2.12.2 ]; then
      sbt ++$TRAVIS_SCALA_VERSION tut
    else
      echo "Skipping sbt tut"
    fi
env:
  global:
    - secure: lJxaR+9VM96s7rfaigL3K2FbcP3XiZ+AerbgOBOpYi2anRkMPQ91h1g60HYTwEDGJIKybyNWFuXZM8hNtQMCxzxgu7ev1SyRr5Otfzg5ehGqB5UWbSAgpXlqhR5dAonwmqyEEDF2OK+k1fa0N6mIwpQeuUCwrt68kTp4f0K9jMQ=
    - secure: NZQn8lB04I+FO3Om680CXWP29scS/zRhITbLO/1sM3dnuG8ygn0fzlFMQhgCO3fCjnclThAi+6MN7UnyV8BwDbFhCDe627+06px5fHUw2TPdzhz/BwngAW9pRsx6m0b8eBqQmt8Q6mlgeYOPemsFOeqQTKZulpIhSYnO1R1Nwzc=
  matrix:
    - TARGET=JVM PRE=test:compile
    - TARGET=JS  PRE=test:fastOptJS
sudo: true
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_install:
 - export PATH=${PATH}:./vendor/bundle
before_script:
  - sudo chmod +x /usr/local/bin/sbt
install:
  - rvm use 2.2.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1
after_success:
- '[[ $TRAVIS_BRANCH == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]] && { sbt +publish ghpagesPushSite; };'
matrix:
  include:
  - scala: 2.11.8
    jdk: oraclejdk8
    sudo: required
    before_install:
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y "deb http://apt.llvm.org/precise/ llvm-toolchain-precise main"
    - sudo add-apt-repository -y "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.7 main"
    - sudo apt-get update -qq
    - sudo apt-get install -y libgc-dev clang++-3.7 llvm-3.7 llvm-3.7-dev llvm-3.7-runtime llvm-3.7-tool libunwind7-dev
    # Install re2
    # https://github.com/scala-native/scala-native/commit/1d312519788534ff41477e4d7f758a6e7451be05#diff-354f30a63fb0907d4ad57269548329e3R28
    - sudo apt-get install -y make
    - export CXX=clang++-3.7
    - git clone https://code.googlesource.com/re2
    - pushd re2
    - git checkout 2017-03-01
    - make -j4 test
    - sudo make install prefix=/usr
    - make testinstall prefix=/usr
    - popd
    script:
    - sbt ++$TRAVIS_SCALA_VERSION testNative/nativeLink
    - ./testNative/target/scala-2.11/monocle-test-native-out
